trigger:
  branches:
    include:
      - master  

pool:
  vmImage: windows-latest  

steps:
  - checkout: self  

  - script: |
      git config --global user.email "frankdezz@gmail.com"
      git config --global user.name "kkhashayar"
      
      
          git remote add github https://kkhashayar:$(GitHubPAT)@github.com/kkhashayar/Engine_Core.git
      
      
      git push github master
    displayName: 'Push Changes to GitHub'
    env:
      GitHubPAT: $(GitHubPAT) 
