trigger:
  branches:
    include:
      - master  # Runs when code is pushed/merged to master

pool:
  vmImage: windows-latest  # Using Windows for .NET projects

variables:
  - group: GitHubSecrets  # Link GitHubPAT variable

steps:
  - checkout: self  # Get latest code from Azure DevOps repo

  - script: |
      git config --global user.email "frankdezz@gmail.com"
      git config --global user.name "kkhashayar"

      # Store GitHub credentials non-interactively
      echo "https://kkhashayar:$(GitHubPAT)@github.com" > ~/.git-credentials
      git config --global credential.helper store

      # Remove old GitHub remote if exists
      git remote remove github || echo "No existing remote"

      # Add GitHub remote using PAT authentication
      git remote add github https://kkhashayar:$(GitHubPAT)@github.com/kkhashayar/Engine_Core.git

      # Ensure correct branch
      git checkout master || git checkout -b master
      git pull github master

      # Push changes from Azure DevOps to GitHub
      git push --set-upstream github master
    displayName: 'Push Changes to GitHub'
    env:
      GitHubPAT: $(GitHubPAT)  # Ensure secure authentication
