trigger:
  branches:
    include:
      - master  

pool:
  vmImage: windows-latest  

steps:
  - checkout: self  

  - script: |
      git config --global user.email "frankdezz@gmail.com"
      git config --global user.name "kkhashayar"

      # Ensure correct branch
      git branch
      git checkout -b master || git checkout master
      git pull origin master
      git remote remove github || echo "No existing remote"
      git remote add github https://kkhashayar:$(GitHubPAT)@github.com/kkhashayar/Engine_Core.git
      git push --set-upstream github master
    displayName: 'Push Changes to GitHub'
    env:
      GitHubPAT: $(GitHubPAT)
