trigger:
  branches:
    include:
      - master  # Runs when code is pushed/merged to master

pool:
  vmImage: windows-latest  # Use Windows for .NET projects

steps:
  - checkout: self  # Get the latest code from Azure DevOps repo

  - script: |
      git config --global user.email "frankdezz@gmail.com"
      git config --global user.name "kkhashayar"

      # Ensure correct branch
      git branch
      git checkout -b master || git checkout master
      git pull origin master

      # Add GitHub as a remote (ensure it's not duplicated)
      git remote remove github || echo "No existing remote"
      git remote add github https://$(GitHubPAT)@github.com/kkhashayar/Engine_Core.git
      git config credential.helper store


      # Push changes from Azure DevOps to GitHub
      git push --set-upstream github master
    displayName: 'Push Changes to GitHub'
    env:
      GitHubPAT: $(GitHubPAT)  # Securely use GitHub token from Azure DevOps Library
