trigger:
  branches:
    include:
      - master  

pool:
  vmImage: windows-latest  

steps:
  - checkout: self  

  - script: |
      git config --global user.email "frankdezz@gmail.com"
      git config --global user.name "kkhashayar"
      
      
      git remote add github https://kkhashayar:$(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)@github.com/kkhashayar/Engine_Core
      
      
      git push github master
    displayName: 'Push Changes to GitHub'
    env:
      GitHubPAT: $(GitHubPAT) 
